/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databasestest;

/**
 *
 * @author jaam
 */
public class MainWindow extends javax.swing.JFrame {
     private SQLiteDB newQuerySQLite;
     private mySQLDB newQueryMySQL;
     private H2DB newQueryH2DB;
     
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        this.jTextArea1.setEditable(false);
        
        //newQuerySQLite = new SQLiteDB();
        //newQueryMySQL = new mySQLDB("TECDB", "root", "root");
        newQueryH2DB = new H2DB("TECDB", "", "");
        newQueryH2DB.execute("CREATE TABLE Personas(Nombre varchar(255),Cedula int primary key)");
        newQueryH2DB.openServerModeInBrowser("TECDB");
    }
    
    private void insertIntoPersonas (int option){
        
        String human ="human";
        
        int cedula=600;
        
        for (int i = 0; i < 1000; i++) {
            String human2 = human + i;
            cedula+=i;
            if (option == 0) {
                newQuerySQLite.insertInto("TECDB", "INSERT INTO Personas(Nombre, Cedula) \n" +
"VALUES('"+human2 +"',"+Integer.toString(cedula)+");");
            } 
            else if (option == 1) {
                newQueryMySQL.execute("INSERT INTO Personas(Nombre, Cedula) \n" +
"VALUES('"+human2 +"',"+Integer.toString(cedula)+");");
            } 
            else {
                newQueryH2DB.execute("INSERT INTO Personas(Nombre, Cedula) \n" +
                "VALUES('"+human2 +"',"+Integer.toString(cedula)+");");

            }
        }
    }
    
    
    private void updatePersonas (int option){
        
        
        String human ="human";
        
        int cedula=600;
        
        for (int i = 0; i < 1000; i++) {
            String human2 = human + i;
            String human3= human +i+i;
            cedula+=i;
            if (option == 0) {
                newQuerySQLite.update("TECDB", "UPDATE Personas set Nombre ="+ human3+" where Nombre='"+human3+"';");
            } 
            else if (option == 1) {
               newQueryMySQL.execute( "UPDATE Personas set Nombre ="+ human3+" where Nombre='"+human3+"';");

            } 
            else {
                newQueryH2DB.execute( "UPDATE Personas set Nombre ="+ human3+" where Nombre='"+human3+"';");
            }
        }
    }
    
     private void selectPersonas (int option) {
        
            if (option == 0) {
                newQuerySQLite.select("TECDB", "SELECT * FROM Personas;");
            } 
            else if (option == 1) {
               newQueryMySQL.execute( "SELECT * FROM Personas;");

            } 
            else {
                newQueryMySQL.execute( "SELECT * FROM Personas; ");
            }
        
    }
     
      private void deletePersonas (int option){
        
            if (option == 0) {
                newQuerySQLite.delete("TECDB", "DELETE from Personas ;");
            } 
            else if (option == 1) {
               newQueryMySQL.execute( "DELETE from Personas ;");

            } 
            else {
                newQueryH2DB.execute( "DELETE from Personas ;");
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        InPerMySQL = new javax.swing.JButton();
        SePerMySQL = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        UpPerMySQL = new javax.swing.JButton();
        dePerMySQL = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        InPerSQLite = new javax.swing.JButton();
        SePerSQLite = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        UpPerSQLite = new javax.swing.JButton();
        dePerSQLite = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        InPerH2DB = new javax.swing.JButton();
        SePerH2DB = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        UpPerH2DB = new javax.swing.JButton();
        dePerH2DB = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        labelGrafico = new javax.swing.JLabel();
        generateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel1.setText("mySQL");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel2.setText("SQLite");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel3.setText("H2DB");

        InPerMySQL.setText("Insert Personas");
        InPerMySQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InPerMySQLMouseClicked(evt);
            }
        });

        SePerMySQL.setText("select * Personas");
        SePerMySQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SePerMySQLMouseClicked(evt);
            }
        });
        SePerMySQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SePerMySQLActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");

        UpPerMySQL.setText("update Personas");
        UpPerMySQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpPerMySQLMouseClicked(evt);
            }
        });

        dePerMySQL.setText("delete Personas");
        dePerMySQL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dePerMySQLMouseClicked(evt);
            }
        });

        jButton6.setText("jButton6");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel4.setText("Output:");

        InPerSQLite.setText("Insert Personas");
        InPerSQLite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InPerSQLiteMouseClicked(evt);
            }
        });

        SePerSQLite.setText("select * Personas");
        SePerSQLite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SePerSQLiteMouseClicked(evt);
            }
        });

        jButton9.setText("jButton9");

        UpPerSQLite.setText("update Personas");
        UpPerSQLite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpPerSQLiteMouseClicked(evt);
            }
        });

        dePerSQLite.setText("delete Personas");
        dePerSQLite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dePerSQLiteMouseClicked(evt);
            }
        });

        jButton12.setText("jButton12");

        InPerH2DB.setText("Insert Personas");
        InPerH2DB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InPerH2DBMouseClicked(evt);
            }
        });

        SePerH2DB.setText("select * Personas");
        SePerH2DB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SePerH2DBMouseClicked(evt);
            }
        });

        jButton15.setText("jButton15");

        UpPerH2DB.setText("update Personas");
        UpPerH2DB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpPerH2DBMouseClicked(evt);
            }
        });

        dePerH2DB.setText("delete Personas");
        dePerH2DB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dePerH2DBMouseClicked(evt);
            }
        });

        jButton18.setText("jButton18");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel5.setText("Results:");

        labelGrafico.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        labelGrafico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGrafico.setText("LabelGrafico");

        generateBtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        generateBtn.setText("Generate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SePerH2DB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dePerH2DB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InPerSQLite, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SePerSQLite, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dePerSQLite, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(UpPerSQLite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SePerMySQL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InPerMySQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InPerH2DB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dePerMySQL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpPerMySQL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(UpPerH2DB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(249, 249, 249)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(generateBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                            .addComponent(labelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InPerMySQL)
                            .addComponent(UpPerMySQL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SePerMySQL)
                            .addComponent(dePerMySQL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InPerSQLite)
                            .addComponent(UpPerSQLite))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SePerSQLite)
                            .addComponent(dePerSQLite))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InPerH2DB)
                            .addComponent(UpPerH2DB))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SePerH2DB)
                            .addComponent(dePerH2DB))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton15)
                            .addComponent(jButton18))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InPerMySQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InPerMySQLMouseClicked
        insertIntoPersonas(1);
    }//GEN-LAST:event_InPerMySQLMouseClicked

    private void InPerSQLiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InPerSQLiteMouseClicked
        insertIntoPersonas(0);
    }//GEN-LAST:event_InPerSQLiteMouseClicked

    private void InPerH2DBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InPerH2DBMouseClicked
                insertIntoPersonas(2);
    }//GEN-LAST:event_InPerH2DBMouseClicked

    private void UpPerMySQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpPerMySQLMouseClicked
            updatePersonas(1);
    }//GEN-LAST:event_UpPerMySQLMouseClicked

    private void UpPerSQLiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpPerSQLiteMouseClicked
        updatePersonas(0);
    }//GEN-LAST:event_UpPerSQLiteMouseClicked

    private void UpPerH2DBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpPerH2DBMouseClicked
                updatePersonas(2);

    }//GEN-LAST:event_UpPerH2DBMouseClicked

    private void SePerMySQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SePerMySQLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SePerMySQLActionPerformed

    private void SePerMySQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SePerMySQLMouseClicked
        selectPersonas(1);
    }//GEN-LAST:event_SePerMySQLMouseClicked

    private void SePerSQLiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SePerSQLiteMouseClicked
        selectPersonas(0);
    }//GEN-LAST:event_SePerSQLiteMouseClicked

    private void SePerH2DBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SePerH2DBMouseClicked
        selectPersonas(2);
    }//GEN-LAST:event_SePerH2DBMouseClicked

    private void dePerMySQLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dePerMySQLMouseClicked
        deletePersonas(1);
    }//GEN-LAST:event_dePerMySQLMouseClicked

    private void dePerSQLiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dePerSQLiteMouseClicked
        deletePersonas(0);
    }//GEN-LAST:event_dePerSQLiteMouseClicked

    private void dePerH2DBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dePerH2DBMouseClicked
        deletePersonas(2);
    }//GEN-LAST:event_dePerH2DBMouseClicked

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InPerH2DB;
    private javax.swing.JButton InPerMySQL;
    private javax.swing.JButton InPerSQLite;
    private javax.swing.JButton SePerH2DB;
    private javax.swing.JButton SePerMySQL;
    private javax.swing.JButton SePerSQLite;
    private javax.swing.JButton UpPerH2DB;
    private javax.swing.JButton UpPerMySQL;
    private javax.swing.JButton UpPerSQLite;
    private javax.swing.JButton dePerH2DB;
    private javax.swing.JButton dePerMySQL;
    private javax.swing.JButton dePerSQLite;
    private javax.swing.JButton generateBtn;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelGrafico;
    // End of variables declaration//GEN-END:variables
}
